# Generated by Django 2.2.6 on 2020-01-30 07:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('vector', django_mysql.models.JSONField(blank=True, default=dict, verbose_name='Векторное представление')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
